name: ECHO

services:
  db:
    ports:
      - "5432:5432"   # local access for psql/GUI

  minio:
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console

  mailhog:
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI at http://localhost:8025

  adminer:
    ports:
      - "8080:8080"   # http://localhost:8080

